/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package airline.management.system;

import javax.swing.JOptionPane;
import java.sql.*;
import java.util.*;
import javax.swing.table.DefaultTableModel;
//import org.apache.commons.dbutils.DbUtils;
/**
 *
 * @author mokhalid
 */
public class Flights extends javax.swing.JFrame {
    Connection Con = null;
    PreparedStatement pst = null;
    ResultSet Rs,Rs1 = null;
    Statement st,st1 = null;
    String selected = "";
    
    /** 
     * Creates new form Flights
     */
    public Flights() {
        initComponents();
        DisplayFlights();
    }
    private boolean MissingData(){
        if (FCode.getText().isEmpty() || FSeats.getText().isEmpty() || FSource.getSelectedIndex() == -1 || FDestination.getSelectedIndex() == -1)
            return true;
        return false;
    }
    private void Clear(){
        FCode.setText("");
        FSeats.setText("");
        
    }
    private void DisplayFlights(){
        try {
            Con = DriverManager.getConnection(Common.DBURL,Common.username,"");
            st = Con.createStatement();
            Rs = st.executeQuery("select * from Flights");
            FTable.setModel(DbUtils.resultSetToTableModel(Rs));
        } catch (Exception e) {
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        FSeats = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        FDate = new com.toedter.calendar.JDateChooser();
        FDestination = new javax.swing.JComboBox<>();
        FCode = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        FSource = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        DeleteBut = new com.k33ptoo.components.KButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        FTable = new javax.swing.JTable();
        AddBut = new com.k33ptoo.components.KButton();
        EditBut = new com.k33ptoo.components.KButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel3.setBackground(new java.awt.Color(22, 33, 62));
        jPanel3.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.setMinimumSize(new java.awt.Dimension(100, 100));
        jPanel3.setPreferredSize(new java.awt.Dimension(400, 80));

        jLabel1.setFont(new java.awt.Font("Waree", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("Manage Flights");
        jPanel3.add(jLabel1);

        jPanel1.add(jPanel3, java.awt.BorderLayout.PAGE_START);

        jPanel2.setBackground(new java.awt.Color(27, 36, 48));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        FSeats.setBackground(new java.awt.Color(204, 204, 204));
        FSeats.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        FSeats.setForeground(new java.awt.Color(22, 33, 62));
        FSeats.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel2.add(FSeats, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 50, 170, 40));

        jLabel3.setFont(new java.awt.Font("Monospaced", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Seats");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 10, -1, -1));
        jPanel2.add(FDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 50, 140, 40));

        FDestination.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        FDestination.setForeground(new java.awt.Color(22, 33, 62));
        FDestination.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Aswan", "Luxor", "Alexandria", "Cairo" }));
        jPanel2.add(FDestination, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 50, 140, 40));

        FCode.setBackground(new java.awt.Color(204, 204, 204));
        FCode.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        FCode.setForeground(new java.awt.Color(22, 33, 62));
        FCode.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel2.add(FCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 170, 40));

        jLabel7.setFont(new java.awt.Font("Monospaced", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Flight Code");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        FSource.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        FSource.setForeground(new java.awt.Color(22, 33, 62));
        FSource.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Aswan", "Luxor", "Alexandria", "Cairo" }));
        jPanel2.add(FSource, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 50, 140, 40));

        jLabel8.setFont(new java.awt.Font("Monospaced", 0, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Source");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 10, -1, -1));

        jLabel9.setFont(new java.awt.Font("Monospaced", 0, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Destination");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 10, -1, -1));

        jLabel10.setFont(new java.awt.Font("Monospaced", 0, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Takeof Date");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 10, -1, -1));

        DeleteBut.setBackground(new java.awt.Color(75, 91, 100));
        DeleteBut.setText("DELETE");
        DeleteBut.setFont(new java.awt.Font("Samanata", 0, 18)); // NOI18N
        DeleteBut.setkBackGroundColor(new java.awt.Color(255, 255, 255));
        DeleteBut.setkBorderRadius(50);
        DeleteBut.setkEndColor(new java.awt.Color(75, 91, 100));
        DeleteBut.setkHoverEndColor(new java.awt.Color(22, 33, 62));
        DeleteBut.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        DeleteBut.setkHoverStartColor(new java.awt.Color(22, 33, 62));
        DeleteBut.setkSelectedColor(new java.awt.Color(75, 91, 100));
        DeleteBut.setkStartColor(new java.awt.Color(75, 91, 100));
        DeleteBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteButActionPerformed(evt);
            }
        });
        jPanel2.add(DeleteBut, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 120, -1, -1));

        FTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        FTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(FTable);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 1110, -1));

        AddBut.setBackground(new java.awt.Color(75, 91, 100));
        AddBut.setText("ADD");
        AddBut.setFont(new java.awt.Font("Samanata", 0, 18)); // NOI18N
        AddBut.setkBackGroundColor(new java.awt.Color(255, 255, 255));
        AddBut.setkBorderRadius(50);
        AddBut.setkEndColor(new java.awt.Color(75, 91, 100));
        AddBut.setkHoverEndColor(new java.awt.Color(22, 33, 62));
        AddBut.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        AddBut.setkHoverStartColor(new java.awt.Color(22, 33, 62));
        AddBut.setkSelectedColor(new java.awt.Color(75, 91, 100));
        AddBut.setkStartColor(new java.awt.Color(75, 91, 100));
        AddBut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddButMouseClicked(evt);
            }
        });
        AddBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddButActionPerformed(evt);
            }
        });
        jPanel2.add(AddBut, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 120, -1, -1));

        EditBut.setBackground(new java.awt.Color(75, 91, 100));
        EditBut.setText("EDIT");
        EditBut.setFont(new java.awt.Font("Samanata", 0, 18)); // NOI18N
        EditBut.setkBackGroundColor(new java.awt.Color(255, 255, 255));
        EditBut.setkBorderRadius(50);
        EditBut.setkEndColor(new java.awt.Color(75, 91, 100));
        EditBut.setkHoverEndColor(new java.awt.Color(22, 33, 62));
        EditBut.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        EditBut.setkHoverStartColor(new java.awt.Color(22, 33, 62));
        EditBut.setkSelectedColor(new java.awt.Color(75, 91, 100));
        EditBut.setkStartColor(new java.awt.Color(75, 91, 100));
        EditBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditButActionPerformed(evt);
            }
        });
        jPanel2.add(EditBut, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 120, -1, -1));

        jPanel1.add(jPanel2, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DeleteButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteButActionPerformed
             if (selected.equals("")){
           JOptionPane.showMessageDialog(this, "Choose flight to delete ! ");
       }else {
                 try {
            String sqlQuery = "delete from Flights where FCode=" + selected;
            Con = DriverManager.getConnection(Common.DBURL,Common.username,"");
            Statement rem = Con.createStatement();
            rem.executeUpdate(sqlQuery);
             JOptionPane.showMessageDialog(this, "Flight Deleted");
             DisplayFlights();
                 } catch (Exception e) {
                      JOptionPane.showMessageDialog(this, e);
                 }
           
       }
    }//GEN-LAST:event_DeleteButActionPerformed
    
    private void AddButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddButActionPerformed
       if (MissingData()){
           JOptionPane.showMessageDialog(this, "Missing Data");
       }
       else {
           try {
            String sqlQuery = "insert into Flights(FCode,FSource,FDestination,FDate,FSeats) values(?,?,?,?,?)";
            Con = DriverManager.getConnection(Common.DBURL,Common.username,"");
            PreparedStatement add = Con.prepareStatement(sqlQuery);
            add.setString(1, FCode.getText());
            add.setString(2, FSource.getSelectedItem().toString());
            add.setString(3, FDestination.getSelectedItem().toString());
             add.setString(4, FDate.getDate().toString());
              add.setInt(5, Integer.valueOf(FSeats.getText()));
              int row = add.executeUpdate();
              JOptionPane.showMessageDialog(this, "Flight Added");
               Con.close();
               DisplayFlights();
               Clear();
              
           } catch (Exception e) {
           }
       }
    }//GEN-LAST:event_AddButActionPerformed

    private void EditButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditButActionPerformed
         if (selected.equals("")){
           JOptionPane.showMessageDialog(this, "Choose flight to edit ! ");
       }else {
                 try {
            String sqlQuery = "update Flights set FSource=?,FDestination=?,FDate=?,FSeats=? where FCode=?";
            Con = DriverManager.getConnection(Common.DBURL,Common.username,"");
            PreparedStatement add = Con.prepareStatement(sqlQuery);
             add.setString(1, FSource.getSelectedItem().toString());
             add.setString(2, FDestination.getSelectedItem().toString());
               add.setString(3, FDate.getDate().toString());
            add.setInt(4, Integer.valueOf(FSeats.getText()));
                add.setString(5, FCode.getText());
          
           
            int row = add.executeUpdate();
             JOptionPane.showMessageDialog(this, "Flight Edited");
             DisplayFlights();
                 } catch (Exception e) {
                      JOptionPane.showMessageDialog(this, e);
                 }
           
       }
    }//GEN-LAST:event_EditButActionPerformed

    private void AddButMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddButMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_AddButMouseClicked

    private void FTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FTableMouseClicked
       DefaultTableModel model = (DefaultTableModel) FTable.getModel();
       int INDEX = FTable.getSelectedRow();
       selected = model.getValueAt(INDEX, 0).toString();
       FCode.setText(model.getValueAt(INDEX, 0).toString());
       FSource.setSelectedItem(model.getValueAt(INDEX, 1).toString());
       FDestination.setSelectedItem(model.getValueAt(INDEX, 2).toString());
     //  FDate.setSelectableDateRange(model.getValueAt(INDEX, 4).toString());
       FSeats.setText(model.getValueAt(INDEX, 4).toString());
      
     
    }//GEN-LAST:event_FTableMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Flights.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Flights.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Flights.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Flights.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Flights().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.k33ptoo.components.KButton AddBut;
    private com.k33ptoo.components.KButton DeleteBut;
    private com.k33ptoo.components.KButton EditBut;
    private javax.swing.JTextField FCode;
    private com.toedter.calendar.JDateChooser FDate;
    private javax.swing.JComboBox<String> FDestination;
    private javax.swing.JTextField FSeats;
    private javax.swing.JComboBox<String> FSource;
    private javax.swing.JTable FTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
