/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package airline.management.system;

import java.awt.Color;
import javax.swing.JOptionPane;
import java.sql.*;
import java.util.*;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
//import org.apache.commons.dbutils.DbUtils;
/**
 *
 * @author mokhalid
 */
public class Flights extends javax.swing.JFrame {
    Connection Con = null;
    PreparedStatement pst = null;
    ResultSet Rs,Rs1 = null;
    Statement st,st1 = null;
    String selected = "";
    
    /** 
     * Creates new form Flights
     */
    public Flights() {
        initComponents();
        DisplayFlights();
    }
    private boolean MissingData(){
        if (FCode.getText().isEmpty() || FSeats.getText().isEmpty() || FSource.getSelectedIndex() == -1 || FDestination.getSelectedIndex() == -1)
            return true;
        return false;
    }
    private void Clear(){
        FCode.setText("");
        FSeats.setText("");
        
    }
    private void DisplayFlights(){
        try {
            Con = DriverManager.getConnection(Common.DBURL,Common.username,"");
            st = Con.createStatement();
            Rs = st.executeQuery("select * from Flights");
            FTable.setModel(DbUtils.resultSetToTableModel(Rs));
        } catch (Exception e) {
        }
    }
    private void setColor(JPanel panell){
        panell.setBackground(new Color(39, 60, 117));
    }
    private void resetColor(JPanel panell){
        panell.setBackground(new Color(52,73,94));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainPanel = new javax.swing.JPanel();
        SidePanel = new javax.swing.JPanel();
        ManageFlights = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        Tickets = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel12 = new javax.swing.JLabel();
        HeadPanel = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        OptionsPanels = new javax.swing.JTabbedPane();
        FlightsPanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        DeleteBut = new com.k33ptoo.components.KButton();
        AddBut = new com.k33ptoo.components.KButton();
        EditBut = new com.k33ptoo.components.KButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        FTable = new javax.swing.JTable();
        FSeats = new javax.swing.JTextField();
        FDate = new com.toedter.calendar.JDateChooser();
        FDestination = new javax.swing.JComboBox<>();
        FSource = new javax.swing.JComboBox<>();
        FCode = new javax.swing.JTextField();
        TicketsPanel = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        DeleteBut1 = new com.k33ptoo.components.KButton();
        AddBut1 = new com.k33ptoo.components.KButton();
        EditBut1 = new com.k33ptoo.components.KButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        FTable1 = new javax.swing.JTable();
        FCode1 = new javax.swing.JTextField();
        FCode2 = new javax.swing.JTextField();
        FSource1 = new javax.swing.JComboBox<>();
        FCode3 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);

        MainPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        SidePanel.setBackground(new java.awt.Color(64, 115, 158));
        SidePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ManageFlights.setBackground(new java.awt.Color(52, 73, 94));
        ManageFlights.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ManageFlightsMouseClicked(evt);
            }
        });
        ManageFlights.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/airline/management/system/Images/icons8-airplane-take-off-50.png"))); // NOI18N
        jLabel2.setPreferredSize(new java.awt.Dimension(50, 70));
        ManageFlights.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, 67));

        jLabel11.setFont(new java.awt.Font("Noto Serif CJK TC", 0, 30)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Manage Flights");
        ManageFlights.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, -1, -1));

        SidePanel.add(ManageFlights, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 320, 60));

        Tickets.setBackground(new java.awt.Color(52, 73, 94));
        Tickets.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TicketsMouseClicked(evt);
            }
        });
        Tickets.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/airline/management/system/Images/icons8-tickets-50.png"))); // NOI18N
        jLabel4.setPreferredSize(new java.awt.Dimension(50, 70));
        Tickets.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, 67));

        jLabel1.setFont(new java.awt.Font("Noto Serif CJK TC", 0, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Tickets");
        Tickets.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, -1, -1));

        SidePanel.add(Tickets, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 320, 60));
        SidePanel.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 290, -1));

        jLabel12.setFont(new java.awt.Font("Noto Serif CJK TC", 1, 30)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(27, 36, 48));
        jLabel12.setText("Airline System");
        SidePanel.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, -1));

        MainPanel.add(SidePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 320, 780));

        HeadPanel.setBackground(new java.awt.Color(52, 73, 94));
        HeadPanel.setForeground(new java.awt.Color(255, 255, 255));
        HeadPanel.setMinimumSize(new java.awt.Dimension(100, 100));
        HeadPanel.setPreferredSize(new java.awt.Dimension(400, 80));
        HeadPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Noto Serif CJK TC", 1, 30)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/airline/management/system/Images/icons8-close-window-48.png"))); // NOI18N
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        HeadPanel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 8, -1, -1));

        MainPanel.add(HeadPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 0, 1050, 60));

        FlightsPanel.setBackground(new java.awt.Color(27, 36, 48));
        FlightsPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Monospaced", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Seats");
        FlightsPanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 40, -1, -1));

        jLabel7.setFont(new java.awt.Font("Monospaced", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Flight Code");
        FlightsPanel.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, -1));

        jLabel8.setFont(new java.awt.Font("Monospaced", 0, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Source");
        FlightsPanel.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 40, -1, -1));

        jLabel9.setFont(new java.awt.Font("Monospaced", 0, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Destination");
        FlightsPanel.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 40, -1, -1));

        jLabel10.setFont(new java.awt.Font("Monospaced", 0, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Takeof Date");
        FlightsPanel.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 40, -1, -1));

        DeleteBut.setBackground(new java.awt.Color(75, 91, 100));
        DeleteBut.setText("DELETE");
        DeleteBut.setFont(new java.awt.Font("Samanata", 0, 18)); // NOI18N
        DeleteBut.setkBackGroundColor(new java.awt.Color(255, 255, 255));
        DeleteBut.setkBorderRadius(50);
        DeleteBut.setkEndColor(new java.awt.Color(75, 91, 100));
        DeleteBut.setkHoverEndColor(new java.awt.Color(22, 33, 62));
        DeleteBut.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        DeleteBut.setkHoverStartColor(new java.awt.Color(22, 33, 62));
        DeleteBut.setkSelectedColor(new java.awt.Color(75, 91, 100));
        DeleteBut.setkStartColor(new java.awt.Color(75, 91, 100));
        DeleteBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteButActionPerformed(evt);
            }
        });
        FlightsPanel.add(DeleteBut, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 150, -1, -1));

        AddBut.setBackground(new java.awt.Color(75, 91, 100));
        AddBut.setText("ADD");
        AddBut.setFont(new java.awt.Font("Samanata", 0, 18)); // NOI18N
        AddBut.setkBackGroundColor(new java.awt.Color(255, 255, 255));
        AddBut.setkBorderRadius(50);
        AddBut.setkEndColor(new java.awt.Color(75, 91, 100));
        AddBut.setkHoverEndColor(new java.awt.Color(22, 33, 62));
        AddBut.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        AddBut.setkHoverStartColor(new java.awt.Color(22, 33, 62));
        AddBut.setkSelectedColor(new java.awt.Color(75, 91, 100));
        AddBut.setkStartColor(new java.awt.Color(75, 91, 100));
        AddBut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddButMouseClicked(evt);
            }
        });
        AddBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddButActionPerformed(evt);
            }
        });
        FlightsPanel.add(AddBut, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, -1, -1));

        EditBut.setBackground(new java.awt.Color(75, 91, 100));
        EditBut.setText("EDIT");
        EditBut.setFont(new java.awt.Font("Samanata", 0, 18)); // NOI18N
        EditBut.setkBackGroundColor(new java.awt.Color(255, 255, 255));
        EditBut.setkBorderRadius(50);
        EditBut.setkEndColor(new java.awt.Color(75, 91, 100));
        EditBut.setkHoverEndColor(new java.awt.Color(22, 33, 62));
        EditBut.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        EditBut.setkHoverStartColor(new java.awt.Color(22, 33, 62));
        EditBut.setkSelectedColor(new java.awt.Color(75, 91, 100));
        EditBut.setkStartColor(new java.awt.Color(75, 91, 100));
        EditBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditButActionPerformed(evt);
            }
        });
        FlightsPanel.add(EditBut, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 150, -1, -1));

        FTable.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        FTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        FTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(FTable);

        FlightsPanel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 1030, 460));

        FSeats.setBackground(new java.awt.Color(204, 204, 204));
        FSeats.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        FSeats.setForeground(new java.awt.Color(22, 33, 62));
        FSeats.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        FlightsPanel.add(FSeats, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 80, 150, 30));
        FlightsPanel.add(FDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 80, 150, 30));

        FDestination.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        FDestination.setForeground(new java.awt.Color(22, 33, 62));
        FDestination.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Aswan", "Luxor", "Alexandria", "Cairo" }));
        FlightsPanel.add(FDestination, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 80, -1, 30));

        FSource.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        FSource.setForeground(new java.awt.Color(22, 33, 62));
        FSource.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Aswan", "Luxor", "Alexandria", "Cairo" }));
        FlightsPanel.add(FSource, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 80, -1, 30));

        FCode.setBackground(new java.awt.Color(204, 204, 204));
        FCode.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        FCode.setForeground(new java.awt.Color(22, 33, 62));
        FCode.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        FlightsPanel.add(FCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 150, 30));

        OptionsPanels.addTab("tab1", FlightsPanel);

        TicketsPanel.setBackground(new java.awt.Color(27, 36, 48));
        TicketsPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Monospaced", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Phone ");
        TicketsPanel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 30, -1, -1));

        jLabel13.setFont(new java.awt.Font("Monospaced", 0, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Passenger Name");
        TicketsPanel.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, -1));

        jLabel15.setFont(new java.awt.Font("Monospaced", 0, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Passport Number");
        TicketsPanel.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 30, -1, -1));

        jLabel16.setFont(new java.awt.Font("Monospaced", 0, 24)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Flight");
        TicketsPanel.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 30, -1, -1));

        DeleteBut1.setBackground(new java.awt.Color(75, 91, 100));
        DeleteBut1.setText("Cancel");
        DeleteBut1.setFont(new java.awt.Font("Samanata", 0, 18)); // NOI18N
        DeleteBut1.setkBackGroundColor(new java.awt.Color(255, 255, 255));
        DeleteBut1.setkBorderRadius(50);
        DeleteBut1.setkEndColor(new java.awt.Color(75, 91, 100));
        DeleteBut1.setkHoverEndColor(new java.awt.Color(22, 33, 62));
        DeleteBut1.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        DeleteBut1.setkHoverStartColor(new java.awt.Color(22, 33, 62));
        DeleteBut1.setkSelectedColor(new java.awt.Color(75, 91, 100));
        DeleteBut1.setkStartColor(new java.awt.Color(75, 91, 100));
        DeleteBut1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteBut1ActionPerformed(evt);
            }
        });
        TicketsPanel.add(DeleteBut1, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 150, -1, -1));

        AddBut1.setBackground(new java.awt.Color(75, 91, 100));
        AddBut1.setText("Pick");
        AddBut1.setFont(new java.awt.Font("Samanata", 0, 18)); // NOI18N
        AddBut1.setkBackGroundColor(new java.awt.Color(255, 255, 255));
        AddBut1.setkBorderRadius(50);
        AddBut1.setkEndColor(new java.awt.Color(75, 91, 100));
        AddBut1.setkHoverEndColor(new java.awt.Color(22, 33, 62));
        AddBut1.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        AddBut1.setkHoverStartColor(new java.awt.Color(22, 33, 62));
        AddBut1.setkSelectedColor(new java.awt.Color(75, 91, 100));
        AddBut1.setkStartColor(new java.awt.Color(75, 91, 100));
        AddBut1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddBut1MouseClicked(evt);
            }
        });
        AddBut1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddBut1ActionPerformed(evt);
            }
        });
        TicketsPanel.add(AddBut1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, -1, -1));

        EditBut1.setBackground(new java.awt.Color(75, 91, 100));
        EditBut1.setText("EDIT");
        EditBut1.setFont(new java.awt.Font("Samanata", 0, 18)); // NOI18N
        EditBut1.setkBackGroundColor(new java.awt.Color(255, 255, 255));
        EditBut1.setkBorderRadius(50);
        EditBut1.setkEndColor(new java.awt.Color(75, 91, 100));
        EditBut1.setkHoverEndColor(new java.awt.Color(22, 33, 62));
        EditBut1.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        EditBut1.setkHoverStartColor(new java.awt.Color(22, 33, 62));
        EditBut1.setkSelectedColor(new java.awt.Color(75, 91, 100));
        EditBut1.setkStartColor(new java.awt.Color(75, 91, 100));
        EditBut1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditBut1ActionPerformed(evt);
            }
        });
        TicketsPanel.add(EditBut1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 150, -1, -1));

        FTable1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        FTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        FTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FTable1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(FTable1);

        TicketsPanel.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 1030, 460));

        FCode1.setBackground(new java.awt.Color(204, 204, 204));
        FCode1.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        FCode1.setForeground(new java.awt.Color(22, 33, 62));
        FCode1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        TicketsPanel.add(FCode1, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 70, 200, 30));

        FCode2.setBackground(new java.awt.Color(204, 204, 204));
        FCode2.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        FCode2.setForeground(new java.awt.Color(22, 33, 62));
        FCode2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        TicketsPanel.add(FCode2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 320, 30));

        FSource1.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        FSource1.setForeground(new java.awt.Color(22, 33, 62));
        FSource1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));
        TicketsPanel.add(FSource1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 70, -1, 30));

        FCode3.setBackground(new java.awt.Color(204, 204, 204));
        FCode3.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        FCode3.setForeground(new java.awt.Color(22, 33, 62));
        FCode3.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        TicketsPanel.add(FCode3, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 70, 160, 30));

        OptionsPanels.addTab("tab1", TicketsPanel);

        MainPanel.add(OptionsPanels, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 20, 1050, 760));
        OptionsPanels.getAccessibleContext().setAccessibleName("");

        getContentPane().add(MainPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DeleteButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteButActionPerformed
             if (selected.equals("")){
           JOptionPane.showMessageDialog(this, "Choose flight to delete ! ");
       }else {
                 try {
            String sqlQuery = "delete from Flights where FCode=" + selected;
            Con = DriverManager.getConnection(Common.DBURL,Common.username,"");
            Statement rem = Con.createStatement();
            rem.executeUpdate(sqlQuery);
             JOptionPane.showMessageDialog(this, "Flight Deleted");
             DisplayFlights();
                 } catch (Exception e) {
                      JOptionPane.showMessageDialog(this, e);
                 }
           
       }
    }//GEN-LAST:event_DeleteButActionPerformed
    
    private void AddButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddButActionPerformed
       if (MissingData()){
           JOptionPane.showMessageDialog(this, "Missing Data");
       }
       else {
           try {
            String sqlQuery = "insert into Flights(FCode,FSource,FDestination,FDate,FSeats) values(?,?,?,?,?)";
            Con = DriverManager.getConnection(Common.DBURL,Common.username,"");
            PreparedStatement add = Con.prepareStatement(sqlQuery);
            add.setString(1, FCode.getText());
            add.setString(2, FSource.getSelectedItem().toString());
            add.setString(3, FDestination.getSelectedItem().toString());
             add.setString(4, FDate.getDate().toString());
              add.setInt(5, Integer.valueOf(FSeats.getText()));
              int row = add.executeUpdate();
              JOptionPane.showMessageDialog(this, "Flight Added");
               Con.close();
               DisplayFlights();
               Clear();
              
           } catch (Exception e) {
           }
       }
    }//GEN-LAST:event_AddButActionPerformed

    private void EditButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditButActionPerformed
         if (selected.equals("")){
           JOptionPane.showMessageDialog(this, "Choose flight to edit ! ");
       }else {
                 try {
            String sqlQuery = "update Flights set FSource=?,FDestination=?,FDate=?,FSeats=? where FCode=?";
            Con = DriverManager.getConnection(Common.DBURL,Common.username,"");
            PreparedStatement add = Con.prepareStatement(sqlQuery);
             add.setString(1, FSource.getSelectedItem().toString());
             add.setString(2, FDestination.getSelectedItem().toString());
               add.setString(3, FDate.getDate().toString());
            add.setInt(4, Integer.valueOf(FSeats.getText()));
                add.setString(5, FCode.getText());
          
           
            int row = add.executeUpdate();
             JOptionPane.showMessageDialog(this, "Flight Edited");
             DisplayFlights();
                 } catch (Exception e) {
                      JOptionPane.showMessageDialog(this, e);
                 }
           
       }
    }//GEN-LAST:event_EditButActionPerformed

    private void AddButMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddButMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_AddButMouseClicked

    private void FTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FTableMouseClicked
       DefaultTableModel model = (DefaultTableModel) FTable.getModel();
       int INDEX = FTable.getSelectedRow();
       selected = model.getValueAt(INDEX, 0).toString();
       FCode.setText(model.getValueAt(INDEX, 0).toString());
       FSource.setSelectedItem(model.getValueAt(INDEX, 1).toString());
       FDestination.setSelectedItem(model.getValueAt(INDEX, 2).toString());
     //  FDate.setSelectableDateRange(model.getValueAt(INDEX, 4).toString());
       FSeats.setText(model.getValueAt(INDEX, 4).toString());
      
     
    }//GEN-LAST:event_FTableMouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel6MouseClicked

    private void ManageFlightsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ManageFlightsMouseClicked
           setColor(ManageFlights);
           resetColor(Tickets);
           OptionsPanels.setSelectedIndex(0);
           
    }//GEN-LAST:event_ManageFlightsMouseClicked

    private void TicketsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TicketsMouseClicked
         setColor(Tickets);
           resetColor(ManageFlights);
            OptionsPanels.setSelectedIndex(1);
    }//GEN-LAST:event_TicketsMouseClicked

    private void DeleteBut1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteBut1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DeleteBut1ActionPerformed

    private void AddBut1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddBut1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_AddBut1MouseClicked

    private void AddBut1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddBut1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddBut1ActionPerformed

    private void EditBut1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditBut1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EditBut1ActionPerformed

    private void FTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FTable1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_FTable1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Flights.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Flights.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Flights.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Flights.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Flights().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.k33ptoo.components.KButton AddBut;
    private com.k33ptoo.components.KButton AddBut1;
    private com.k33ptoo.components.KButton DeleteBut;
    private com.k33ptoo.components.KButton DeleteBut1;
    private com.k33ptoo.components.KButton EditBut;
    private com.k33ptoo.components.KButton EditBut1;
    private javax.swing.JTextField FCode;
    private javax.swing.JTextField FCode1;
    private javax.swing.JTextField FCode2;
    private javax.swing.JTextField FCode3;
    private com.toedter.calendar.JDateChooser FDate;
    private javax.swing.JComboBox<String> FDestination;
    private javax.swing.JTextField FSeats;
    private javax.swing.JComboBox<String> FSource;
    private javax.swing.JComboBox<String> FSource1;
    private javax.swing.JTable FTable;
    private javax.swing.JTable FTable1;
    private javax.swing.JPanel FlightsPanel;
    private javax.swing.JPanel HeadPanel;
    private javax.swing.JPanel MainPanel;
    private javax.swing.JPanel ManageFlights;
    private javax.swing.JTabbedPane OptionsPanels;
    private javax.swing.JPanel SidePanel;
    private javax.swing.JPanel Tickets;
    private javax.swing.JPanel TicketsPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
