/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package airline.management.system;

import com.sun.jdi.connect.spi.Connection;
import java.sql.DriverManager;
import javax.swing.JOptionPane;

/**
 *
 * @author mokhalid
 */
public class LogIn extends javax.swing.JFrame {
    
    // Movable Form : 
    int xPosition = 0 , yPosition = 0;
    
    public LogIn() {
        initComponents();
    }
 private boolean MissingData(){
        if (Username.getText().isEmpty() || Password.getText().isEmpty())
            return true;
        return false;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel1 = new keeptoo.KGradientPanel();
        Username = new javax.swing.JTextField();
        Password = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        LogInBut = new com.k33ptoo.components.KButton();
        ExitBut1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        kGradientPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        kGradientPanel1.setkEndColor(new java.awt.Color(22, 33, 62));
        kGradientPanel1.setkGradientFocus(200);
        kGradientPanel1.setkStartColor(new java.awt.Color(27, 36, 48));
        kGradientPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Username.setBackground(new java.awt.Color(0,0,0,0));
        Username.setFont(new java.awt.Font("Manjari Bold", 0, 24)); // NOI18N
        Username.setForeground(new java.awt.Color(255, 255, 255));
        Username.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        Username.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        kGradientPanel1.add(Username, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 160, 268, 44));

        Password.setBackground(new java.awt.Color(0,0,0,0));
        Password.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        Password.setForeground(new java.awt.Color(255, 255, 255));
        Password.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        kGradientPanel1.add(Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 290, 270, 40));

        jLabel1.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("password");
        kGradientPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 250, -1, -1));

        LogInBut.setBackground(new java.awt.Color(233, 69, 96));
        LogInBut.setText("Sign in");
        LogInBut.setFont(new java.awt.Font("Nimbus Mono L", 0, 24)); // NOI18N
        LogInBut.setkBorderRadius(50);
        LogInBut.setkEndColor(new java.awt.Color(233, 69, 96));
        LogInBut.setkFillButton(false);
        LogInBut.setkHoverEndColor(new java.awt.Color(75, 91, 100));
        LogInBut.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        LogInBut.setkHoverStartColor(new java.awt.Color(75, 91, 100));
        LogInBut.setkStartColor(new java.awt.Color(233, 69, 96));
        LogInBut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LogInButMouseClicked(evt);
            }
        });
        LogInBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogInButActionPerformed(evt);
            }
        });
        kGradientPanel1.add(LogInBut, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 370, -1, -1));

        ExitBut1.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        ExitBut1.setForeground(new java.awt.Color(255, 255, 255));
        ExitBut1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/airline/management/system/Images/icons8-close-window-48.png"))); // NOI18N
        ExitBut1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ExitBut1MouseClicked(evt);
            }
        });
        kGradientPanel1.add(ExitBut1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 10, -1, -1));

        jLabel7.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/airline/management/system/Images/icons8-male-user-50.png"))); // NOI18N
        kGradientPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 70, -1, -1));

        jLabel8.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("username");
        kGradientPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 130, -1, -1));

        getContentPane().add(kGradientPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 678, 486));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LogInButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogInButActionPerformed
       
    }//GEN-LAST:event_LogInButActionPerformed

    private void LogInButMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogInButMouseClicked
        if (MissingData()){
           JOptionPane.showMessageDialog(this, "Missing Data");
       }
        else {
            if (!Username.getText().toString().equals("admin")){
                JOptionPane.showMessageDialog(this, "Invalid Username");
                Username.setText("");
            }
            else if (!Password.getText().toString().equals("admin")){
                JOptionPane.showMessageDialog(this, "Invalid Password");
                 Password.setText("");
            }
            else{
              new SystemMain().setVisible(true);
              this.dispose();
            }
             {
            }
        }
    }//GEN-LAST:event_LogInButMouseClicked

    private void ExitBut1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitBut1MouseClicked
       System.exit(0);
    }//GEN-LAST:event_ExitBut1MouseClicked

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
       xPosition = evt.getX();
       yPosition = evt.getY();
    }//GEN-LAST:event_formMousePressed

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        setLocation(evt.getXOnScreen() - xPosition, evt.getYOnScreen() -yPosition);
    }//GEN-LAST:event_formMouseDragged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LogIn().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ExitBut1;
    private com.k33ptoo.components.KButton LogInBut;
    private javax.swing.JPasswordField Password;
    private javax.swing.JTextField Username;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private keeptoo.KGradientPanel kGradientPanel1;
    // End of variables declaration//GEN-END:variables
}
