/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package airline.management.system;

import java.awt.Color;
import javax.swing.JOptionPane;
import java.sql.*;
import java.util.*;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
//import org.apache.commons.dbutils.DbUtils;
/**
 *
 * @author mokhalid
 */
public class SystemMain extends javax.swing.JFrame {
    
    String Flightselected = "";
    String Passengerselected = "";
    int xPosition = 0 , yPosition = 0;
    FlightsClass newFlight = null;
    PassengerClass newPassenger = null;
    
    public SystemMain() {
        initComponents();
        DisplayFlights();
        DisplayPassengers();
        GetFlightsCodes();
    }
    
    // Check Methods : 
    private boolean MissingFlightData(){
        if (FCode.getText().isEmpty() || FSeats.getText().isEmpty() || FSource.getSelectedIndex() == -1 || FDestination.getSelectedIndex() == -1)
            return true;
        if( FSource.getSelectedIndex() == FDestination.getSelectedIndex()) return true;
        return false;
    }
    private boolean MissingPassengerData(){
        if (PassName.getText().isEmpty() || PassportNum.getText().isEmpty() || FlightCodeChoices.getSelectedIndex() == -1 || PhoneNumber.getText().isEmpty())
            return true;
        return false;
    }
    private void FlightsClear(){
        FCode.setText("");
        FSeats.setText("");
    }
    private void PassengersClear(){
        PassName.setText("");
        PassportNum.setText("");
         PhoneNumber.setText("");
    }
    
  
    // Display Methods : 
    private void DisplayFlights(){
        try {
            Common.Con = DriverManager.getConnection(Common.DBURL,Common.username,"");
            Common.st = Common.Con.createStatement();
            Common.Rs = Common.st.executeQuery("select * from Flights");
            FTable.setModel(DbUtils.resultSetToTableModel(Common.Rs));
        } catch (Exception e) {
        }
    }
     private void DisplayPassengers(){
        try {
            Common.Con = DriverManager.getConnection(Common.DBURL,Common.username,"");
            Common.st = Common.Con.createStatement();
            Common.Rs = Common.st.executeQuery("select * from Passengers");
            PassTable.setModel(DbUtils.resultSetToTableModel(Common.Rs));
        } catch (Exception e) {
        }
    }
     private void GetFlightsCodes(){
          try {
            FlightsClass.FlightsCodes();
            FlightCodeChoices.removeAllItems();
             while(Common.Rs.next()){
                String FlightCd = Common.Rs.getString("FCode");
                // Check Seats before adding : 
                if (FlightsClass.SeatsCheck(FlightCd))
                    FlightCodeChoices.addItem(FlightCd);   
            }
        } catch (Exception e) {
        }   
     }
     
    private void setColor(JPanel panell){
        panell.setBackground(new Color(39, 60, 117));
    }
    private void resetColor(JPanel panell){
        panell.setBackground(new Color(52,73,94));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainPanel = new javax.swing.JPanel();
        SidePanel = new javax.swing.JPanel();
        ManageFlights = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        Tickets = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel12 = new javax.swing.JLabel();
        HeadPanel = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        OptionsPanels = new javax.swing.JTabbedPane();
        FlightsPanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        DeleteBut = new com.k33ptoo.components.KButton();
        AddBut = new com.k33ptoo.components.KButton();
        EditBut = new com.k33ptoo.components.KButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        FTable = new javax.swing.JTable();
        FSeats = new javax.swing.JTextField();
        FDate = new com.toedter.calendar.JDateChooser();
        FDestination = new javax.swing.JComboBox<>();
        FSource = new javax.swing.JComboBox<>();
        FCode = new javax.swing.JTextField();
        TicketsPanel = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        EditPassBut = new com.k33ptoo.components.KButton();
        PickBut = new com.k33ptoo.components.KButton();
        PassDeleteBut = new com.k33ptoo.components.KButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        PassTable = new javax.swing.JTable();
        PhoneNumber = new javax.swing.JTextField();
        PassName = new javax.swing.JTextField();
        FlightCodeChoices = new javax.swing.JComboBox<>();
        PassportNum = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        MainPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        SidePanel.setBackground(new java.awt.Color(64, 115, 158));
        SidePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ManageFlights.setBackground(new java.awt.Color(52, 73, 94));
        ManageFlights.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ManageFlightsMouseClicked(evt);
            }
        });
        ManageFlights.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/airline/management/system/Images/icons8-airplane-take-off-50.png"))); // NOI18N
        jLabel2.setPreferredSize(new java.awt.Dimension(50, 70));
        ManageFlights.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, 67));

        jLabel11.setFont(new java.awt.Font("Noto Serif CJK TC", 0, 30)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Manage Flights");
        ManageFlights.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, -1, -1));

        SidePanel.add(ManageFlights, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 320, 60));

        Tickets.setBackground(new java.awt.Color(52, 73, 94));
        Tickets.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TicketsMouseClicked(evt);
            }
        });
        Tickets.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/airline/management/system/Images/icons8-tickets-50.png"))); // NOI18N
        jLabel4.setPreferredSize(new java.awt.Dimension(50, 70));
        Tickets.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, 67));

        jLabel1.setFont(new java.awt.Font("Noto Serif CJK TC", 0, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Tickets");
        Tickets.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, -1, -1));

        SidePanel.add(Tickets, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 320, 60));
        SidePanel.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 290, -1));

        jLabel12.setFont(new java.awt.Font("Noto Serif CJK TC", 1, 30)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(27, 36, 48));
        jLabel12.setText("Airline System");
        SidePanel.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, -1));

        MainPanel.add(SidePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 320, 780));

        HeadPanel.setBackground(new java.awt.Color(52, 73, 94));
        HeadPanel.setForeground(new java.awt.Color(255, 255, 255));
        HeadPanel.setMinimumSize(new java.awt.Dimension(100, 100));
        HeadPanel.setPreferredSize(new java.awt.Dimension(400, 80));
        HeadPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Noto Serif CJK TC", 1, 30)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/airline/management/system/Images/icons8-close-window-48.png"))); // NOI18N
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        HeadPanel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 8, -1, -1));

        MainPanel.add(HeadPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 0, 1050, 20));

        FlightsPanel.setBackground(new java.awt.Color(27, 36, 48));
        FlightsPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Monospaced", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Seats");
        FlightsPanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 40, -1, -1));

        jLabel7.setFont(new java.awt.Font("Monospaced", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Flight Code");
        FlightsPanel.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, -1));

        jLabel8.setFont(new java.awt.Font("Monospaced", 0, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Source");
        FlightsPanel.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 40, -1, -1));

        jLabel9.setFont(new java.awt.Font("Monospaced", 0, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Destination");
        FlightsPanel.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 40, -1, -1));

        jLabel10.setFont(new java.awt.Font("Monospaced", 0, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Takeof Date");
        FlightsPanel.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 40, -1, -1));

        DeleteBut.setBackground(new java.awt.Color(75, 91, 100));
        DeleteBut.setText("DELETE");
        DeleteBut.setFont(new java.awt.Font("Samanata", 0, 18)); // NOI18N
        DeleteBut.setkBackGroundColor(new java.awt.Color(255, 255, 255));
        DeleteBut.setkBorderRadius(50);
        DeleteBut.setkEndColor(new java.awt.Color(75, 91, 100));
        DeleteBut.setkHoverEndColor(new java.awt.Color(22, 33, 62));
        DeleteBut.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        DeleteBut.setkHoverStartColor(new java.awt.Color(22, 33, 62));
        DeleteBut.setkSelectedColor(new java.awt.Color(75, 91, 100));
        DeleteBut.setkStartColor(new java.awt.Color(75, 91, 100));
        DeleteBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteButActionPerformed(evt);
            }
        });
        FlightsPanel.add(DeleteBut, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 150, -1, -1));

        AddBut.setBackground(new java.awt.Color(75, 91, 100));
        AddBut.setText("ADD");
        AddBut.setFont(new java.awt.Font("Samanata", 0, 18)); // NOI18N
        AddBut.setkBackGroundColor(new java.awt.Color(255, 255, 255));
        AddBut.setkBorderRadius(50);
        AddBut.setkEndColor(new java.awt.Color(75, 91, 100));
        AddBut.setkHoverEndColor(new java.awt.Color(22, 33, 62));
        AddBut.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        AddBut.setkHoverStartColor(new java.awt.Color(22, 33, 62));
        AddBut.setkSelectedColor(new java.awt.Color(75, 91, 100));
        AddBut.setkStartColor(new java.awt.Color(75, 91, 100));
        AddBut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddButMouseClicked(evt);
            }
        });
        AddBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddButActionPerformed(evt);
            }
        });
        FlightsPanel.add(AddBut, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, -1, -1));

        EditBut.setBackground(new java.awt.Color(75, 91, 100));
        EditBut.setText("EDIT");
        EditBut.setFont(new java.awt.Font("Samanata", 0, 18)); // NOI18N
        EditBut.setkBackGroundColor(new java.awt.Color(255, 255, 255));
        EditBut.setkBorderRadius(50);
        EditBut.setkEndColor(new java.awt.Color(75, 91, 100));
        EditBut.setkHoverEndColor(new java.awt.Color(22, 33, 62));
        EditBut.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        EditBut.setkHoverStartColor(new java.awt.Color(22, 33, 62));
        EditBut.setkSelectedColor(new java.awt.Color(75, 91, 100));
        EditBut.setkStartColor(new java.awt.Color(75, 91, 100));
        EditBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditButActionPerformed(evt);
            }
        });
        FlightsPanel.add(EditBut, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 150, -1, -1));

        FTable.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        FTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        FTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(FTable);

        FlightsPanel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 1030, 460));

        FSeats.setBackground(new java.awt.Color(204, 204, 204));
        FSeats.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        FSeats.setForeground(new java.awt.Color(22, 33, 62));
        FSeats.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        FlightsPanel.add(FSeats, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 80, 150, 30));
        FlightsPanel.add(FDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 80, 150, 30));

        FDestination.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        FDestination.setForeground(new java.awt.Color(22, 33, 62));
        FDestination.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Aswan", "Luxor", "Alexandria", "Cairo" }));
        FlightsPanel.add(FDestination, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 80, -1, 30));

        FSource.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        FSource.setForeground(new java.awt.Color(22, 33, 62));
        FSource.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Aswan", "Luxor", "Alexandria", "Cairo" }));
        FlightsPanel.add(FSource, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 80, -1, 30));

        FCode.setBackground(new java.awt.Color(204, 204, 204));
        FCode.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        FCode.setForeground(new java.awt.Color(22, 33, 62));
        FCode.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        FlightsPanel.add(FCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 150, 30));

        OptionsPanels.addTab("tab1", FlightsPanel);

        TicketsPanel.setBackground(new java.awt.Color(27, 36, 48));
        TicketsPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Monospaced", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Phone ");
        TicketsPanel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 30, -1, -1));

        jLabel13.setFont(new java.awt.Font("Monospaced", 0, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Passenger Name");
        TicketsPanel.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, -1));

        jLabel15.setFont(new java.awt.Font("Monospaced", 0, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Passport Number");
        TicketsPanel.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 30, -1, -1));

        jLabel16.setFont(new java.awt.Font("Monospaced", 0, 24)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Flight");
        TicketsPanel.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 30, -1, -1));

        EditPassBut.setBackground(new java.awt.Color(75, 91, 100));
        EditPassBut.setText("EDIT");
        EditPassBut.setFont(new java.awt.Font("Samanata", 0, 18)); // NOI18N
        EditPassBut.setkBackGroundColor(new java.awt.Color(255, 255, 255));
        EditPassBut.setkBorderRadius(50);
        EditPassBut.setkEndColor(new java.awt.Color(75, 91, 100));
        EditPassBut.setkHoverEndColor(new java.awt.Color(22, 33, 62));
        EditPassBut.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        EditPassBut.setkHoverStartColor(new java.awt.Color(22, 33, 62));
        EditPassBut.setkSelectedColor(new java.awt.Color(75, 91, 100));
        EditPassBut.setkStartColor(new java.awt.Color(75, 91, 100));
        EditPassBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditPassButActionPerformed(evt);
            }
        });
        TicketsPanel.add(EditPassBut, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 150, -1, -1));

        PickBut.setBackground(new java.awt.Color(75, 91, 100));
        PickBut.setText("Pick");
        PickBut.setFont(new java.awt.Font("Samanata", 0, 18)); // NOI18N
        PickBut.setkBackGroundColor(new java.awt.Color(255, 255, 255));
        PickBut.setkBorderRadius(50);
        PickBut.setkEndColor(new java.awt.Color(75, 91, 100));
        PickBut.setkHoverEndColor(new java.awt.Color(22, 33, 62));
        PickBut.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        PickBut.setkHoverStartColor(new java.awt.Color(22, 33, 62));
        PickBut.setkSelectedColor(new java.awt.Color(75, 91, 100));
        PickBut.setkStartColor(new java.awt.Color(75, 91, 100));
        PickBut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PickButMouseClicked(evt);
            }
        });
        PickBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PickButActionPerformed(evt);
            }
        });
        TicketsPanel.add(PickBut, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, -1, -1));

        PassDeleteBut.setBackground(new java.awt.Color(75, 91, 100));
        PassDeleteBut.setText("DELETE");
        PassDeleteBut.setFont(new java.awt.Font("Samanata", 0, 18)); // NOI18N
        PassDeleteBut.setkBackGroundColor(new java.awt.Color(255, 255, 255));
        PassDeleteBut.setkBorderRadius(50);
        PassDeleteBut.setkEndColor(new java.awt.Color(75, 91, 100));
        PassDeleteBut.setkHoverEndColor(new java.awt.Color(22, 33, 62));
        PassDeleteBut.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        PassDeleteBut.setkHoverStartColor(new java.awt.Color(22, 33, 62));
        PassDeleteBut.setkSelectedColor(new java.awt.Color(75, 91, 100));
        PassDeleteBut.setkStartColor(new java.awt.Color(75, 91, 100));
        PassDeleteBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PassDeleteButActionPerformed(evt);
            }
        });
        TicketsPanel.add(PassDeleteBut, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 150, -1, -1));

        PassTable.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        PassTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        PassTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PassTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(PassTable);

        TicketsPanel.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 1030, 470));

        PhoneNumber.setBackground(new java.awt.Color(204, 204, 204));
        PhoneNumber.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        PhoneNumber.setForeground(new java.awt.Color(22, 33, 62));
        PhoneNumber.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        TicketsPanel.add(PhoneNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 70, 200, 30));

        PassName.setBackground(new java.awt.Color(204, 204, 204));
        PassName.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        PassName.setForeground(new java.awt.Color(22, 33, 62));
        PassName.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        TicketsPanel.add(PassName, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 320, 30));

        FlightCodeChoices.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        FlightCodeChoices.setForeground(new java.awt.Color(22, 33, 62));
        TicketsPanel.add(FlightCodeChoices, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 70, 100, 30));

        PassportNum.setBackground(new java.awt.Color(204, 204, 204));
        PassportNum.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        PassportNum.setForeground(new java.awt.Color(22, 33, 62));
        PassportNum.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        TicketsPanel.add(PassportNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 70, 160, 30));

        OptionsPanels.addTab("tab1", TicketsPanel);

        MainPanel.add(OptionsPanels, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 20, 1050, 760));
        OptionsPanels.getAccessibleContext().setAccessibleName("");

        getContentPane().add(MainPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DeleteButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteButActionPerformed
             if (Flightselected.equals("")){
           JOptionPane.showMessageDialog(this, "Choose flight to delete ! ");
       }else {
                 try {
           newFlight = new FlightsClass(FCode.getText(), FSource.getSelectedItem().toString(),
                FDestination.getSelectedItem().toString(), FDate.getDate().toString(), Integer.valueOf(FSeats.getText()));
           newFlight.DeleteFlight(Flightselected);
             JOptionPane.showMessageDialog(this, "Flight Deleted");
             DisplayFlights();
             FlightsClear();
             GetFlightsCodes();
                 } catch (Exception e) {
                      JOptionPane.showMessageDialog(this, e);
                 }
           
       }
    }//GEN-LAST:event_DeleteButActionPerformed
    
    private void AddButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddButActionPerformed
       if (MissingFlightData()){
           JOptionPane.showMessageDialog(this, "Missing Data");
       }
       else {
           try {
               newFlight = new FlightsClass(FCode.getText(), FSource.getSelectedItem().toString(),
                FDestination.getSelectedItem().toString(), FDate.getDate().toString(), Integer.valueOf(FSeats.getText()));
               newFlight.InsertFlight();
               JOptionPane.showMessageDialog(this, "Flight Added");  
               DisplayFlights();
               FlightsClear();
               GetFlightsCodes();
           } catch (Exception e) {
           }
       }
    }//GEN-LAST:event_AddButActionPerformed

    private void EditButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditButActionPerformed
         if (Flightselected.equals("")){
           JOptionPane.showMessageDialog(this, "Choose flight to edit ! ");
       }else {
                 try {
          newFlight = new FlightsClass(FCode.getText(), FSource.getSelectedItem().toString(),
                FDestination.getSelectedItem().toString(), FDate.getDate().toString(), Integer.valueOf(FSeats.getText()));
          newFlight.EditFlight();
             JOptionPane.showMessageDialog(this, "Flight Edited");
             DisplayFlights();
             FlightsClear();
             GetFlightsCodes();
                 } catch (Exception e) {
                      JOptionPane.showMessageDialog(this, e);
                 }
           
       }
    }//GEN-LAST:event_EditButActionPerformed

    private void AddButMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddButMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_AddButMouseClicked

    private void FTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FTableMouseClicked
       DefaultTableModel model = (DefaultTableModel) FTable.getModel();
       int INDEX = FTable.getSelectedRow();
       Flightselected = model.getValueAt(INDEX, 0).toString();
       FCode.setText(model.getValueAt(INDEX, 0).toString());
       FSource.setSelectedItem(model.getValueAt(INDEX, 1).toString());
       FDestination.setSelectedItem(model.getValueAt(INDEX, 2).toString());
     // FDate.setSelectableDateRange(model.getValueAt(INDEX, 4).toString());
       FSeats.setText(model.getValueAt(INDEX, 4).toString()); 
    }//GEN-LAST:event_FTableMouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel6MouseClicked

    private void ManageFlightsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ManageFlightsMouseClicked
           setColor(ManageFlights);
           resetColor(Tickets);
           OptionsPanels.setSelectedIndex(0);
           
    }//GEN-LAST:event_ManageFlightsMouseClicked

    private void TicketsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TicketsMouseClicked
         setColor(Tickets);
           resetColor(ManageFlights);
            OptionsPanels.setSelectedIndex(1);
    }//GEN-LAST:event_TicketsMouseClicked

    private void EditPassButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditPassButActionPerformed
         if (Passengerselected.equals("")){
           JOptionPane.showMessageDialog(this, "Choose passenger to edit ! ");
       }else {
                 try {
                     newPassenger = new PassengerClass(PassName.getText(), FlightCodeChoices.getSelectedItem().toString(),
                             PhoneNumber.getText(), PassportNum.getText());
                     newPassenger.EditPassenger(Passengerselected);
             JOptionPane.showMessageDialog(this, "Passenger Edited");
             DisplayPassengers();
             PassengersClear();
                 } catch (Exception e) {
                      JOptionPane.showMessageDialog(this, e);
                 }
           
       }
    }//GEN-LAST:event_EditPassButActionPerformed

    private void PickButMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PickButMouseClicked
         if (MissingPassengerData()){
           JOptionPane.showMessageDialog(this, "Missing Data");
       }
       else {
           try {
                newPassenger = new PassengerClass(PassName.getText(), FlightCodeChoices.getSelectedItem().toString()
                , PhoneNumber.getText(), PassportNum.getText());
             newPassenger.PickFlight();
              JOptionPane.showMessageDialog(this, "Ticket Picked");
               FlightsClass.UpdateSeats("pick",FlightCodeChoices.getSelectedItem().toString());
               DisplayFlights();
               DisplayPassengers();
               PassengersClear();
           } catch (Exception e) {
           }
       }
    }//GEN-LAST:event_PickButMouseClicked

    private void PickButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PickButActionPerformed
      
    }//GEN-LAST:event_PickButActionPerformed

    private void PassDeleteButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PassDeleteButActionPerformed
          if (Passengerselected.equals("")){
           JOptionPane.showMessageDialog(this, "Choose passenger to delete ! ");
       }else {
                 try {
                      newPassenger = new PassengerClass(PassName.getText(), FlightCodeChoices.getSelectedItem().toString(),
                             PhoneNumber.getText(), PassportNum.getText());
           newPassenger.DeletePassenger(Passengerselected);
             JOptionPane.showMessageDialog(this, "Passenger Deleted");
              DisplayPassengers();
              PassengersClear();
                 } catch (Exception e) {
                      JOptionPane.showMessageDialog(this, e);
                 }
           
       }
    }//GEN-LAST:event_PassDeleteButActionPerformed

    private void PassTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PassTableMouseClicked
        DefaultTableModel model = (DefaultTableModel) PassTable.getModel();
       int INDEX = PassTable.getSelectedRow();
       Passengerselected = model.getValueAt(INDEX, 0).toString();
          PassName.setText(model.getValueAt(INDEX, 1).toString());
           PassportNum.setText(model.getValueAt(INDEX, 2).toString());
            PhoneNumber.setText(model.getValueAt(INDEX, 3).toString());
       FSource.setSelectedItem(model.getValueAt(INDEX, 4).toString());
    }//GEN-LAST:event_PassTableMouseClicked

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        xPosition = evt.getX();
        yPosition = evt.getY();
    }//GEN-LAST:event_formMouseClicked

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
         setLocation(evt.getXOnScreen() - xPosition, evt.getYOnScreen() -yPosition);
    }//GEN-LAST:event_formMouseDragged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SystemMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SystemMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SystemMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SystemMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SystemMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.k33ptoo.components.KButton AddBut;
    private com.k33ptoo.components.KButton DeleteBut;
    private com.k33ptoo.components.KButton EditBut;
    private com.k33ptoo.components.KButton EditPassBut;
    private javax.swing.JTextField FCode;
    private com.toedter.calendar.JDateChooser FDate;
    private javax.swing.JComboBox<String> FDestination;
    private javax.swing.JTextField FSeats;
    private javax.swing.JComboBox<String> FSource;
    private javax.swing.JTable FTable;
    private javax.swing.JComboBox<String> FlightCodeChoices;
    private javax.swing.JPanel FlightsPanel;
    private javax.swing.JPanel HeadPanel;
    private javax.swing.JPanel MainPanel;
    private javax.swing.JPanel ManageFlights;
    private javax.swing.JTabbedPane OptionsPanels;
    private com.k33ptoo.components.KButton PassDeleteBut;
    private javax.swing.JTextField PassName;
    private javax.swing.JTable PassTable;
    private javax.swing.JTextField PassportNum;
    private javax.swing.JTextField PhoneNumber;
    private com.k33ptoo.components.KButton PickBut;
    private javax.swing.JPanel SidePanel;
    private javax.swing.JPanel Tickets;
    private javax.swing.JPanel TicketsPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
